// app/(quote-preview)/quote/[id]/page.jsx
// Quote Preview Page with dynamic OG metadata for social sharing

import { createClient } from '@supabase/supabase-js';
import QuotePreviewClient from './QuotePreviewClient';

// Create Supabase client for server-side
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
);

// Generate dynamic metadata for social sharing
export async function generateMetadata({ params }) {
  const { id } = await params;

  try {
    const { data: quote, error } = await supabase
      .from('quotes')
      .select('title, client_name, reference, pricing, monthly_price, quote_type, service_type, project_overview')
      .eq('id', id)
      .single();

    if (error || !quote) {
      return {
        title: 'Ponuda | NineFold',
        description: 'Pregled ponude',
      };
    }

    const isMonthly = quote.quote_type === 'monthly';
    const price = isMonthly
      ? quote.monthly_price
      : quote.pricing?.total;

    const title = quote.title || `Ponuda za ${quote.client_name}`;
    const description = quote.project_overview
      ? quote.project_overview.substring(0, 160) + (quote.project_overview.length > 160 ? '...' : '')
      : `Poslovna ponuda pripremljena za ${quote.client_name}`;

    // Service type labels in Croatian
    const serviceLabels = {
      web_development: 'Web Development',
      ui_ux_design: 'UI/UX Dizajn',
      branding: 'Branding',
      digital_marketing: 'Digitalni Marketing',
      consulting: 'Konzalting',
      maintenance: 'Održavanje',
    };
    const serviceLabel = serviceLabels[quote.service_type] || 'Usluga';

    return {
      title: `${title} | NineFold`,
      description,
      openGraph: {
        title: `${title}`,
        description,
        siteName: 'NineFold',
        type: 'website',
        locale: 'hr_HR',
        // OG image is auto-generated by opengraph-image.jsx
      },
      twitter: {
        card: 'summary_large_image',
        title: `${title}`,
        description,
        // Twitter image is auto-generated by twitter-image.jsx
      },
      other: {
        'og:price:amount': price?.toString() || '',
        'og:price:currency': 'EUR',
      },
    };
  } catch (error) {
    console.error('Error generating metadata:', error);
    return {
      title: 'Ponuda | NineFold',
      description: 'Pregled ponude',
    };
  }
}

export default function QuotePreviewPage() {
  return <QuotePreviewClient />;
}
