// Landing pages za Google Ads kampanje: /izrada-web-stranica i /izrada-web-shopa.
// Plain module (no JSX) so server components can import it for metadata.
// Cijene su NAMJERNO odvojene od lib/salesPackages.js (Karlovi prodajni paketi):
// landing prikazuje standardni Ninefold cjenik, postavljen prema stvarnim ponudama.

const PRICES = {
  webStart: 1290,
  webStandard: 2490,
  webPremium: 4490,
  shopMini: 1990,
  shopCustomFrom: 3990,
}

const eur = (n) => `${n.toLocaleString('hr-HR')} €`

export const LANDINGS = {
  'izrada-web-stranica': {
    slug: 'izrada-web-stranica',
    chip: 'Izrada web stranica',
    metaTitle: `Izrada web stranica od ${eur(PRICES.webStart)} | Ninefold`,
    metaDescription: `Profesionalna izrada web stranica. Custom dizajn, SEO od prvog dana i brzina ispod sekunde. Paketi od ${eur(PRICES.webStart)}, cijena poznata unaprijed.`,
    h1: 'Izrada web stranica koje dovode klijente.',
    sub: 'Custom dizajn, brzina ispod sekunde i SEO od prvog dana. Cijenu znaš unaprijed, a stranicu dobiješ u par tjedana, ne mjeseci.',
    heroPills: [`Paketi od ${eur(PRICES.webStart)}`, 'Izrada od 2 tjedna', 'Odgovor unutar 24 sata'],
    benefits: [
      { title: 'Custom dizajn', note: 'Bez predložaka i tema. Dizajn koji izgleda kao tvoj brend, ne kao još jedan template.' },
      { title: 'Brzina koja se mjeri', note: 'Stranice se otvaraju ispod sekunde. Google to nagrađuje, posjetitelji još više.' },
      { title: 'SEO od prvog dana', note: 'Struktura, sadržaj i tehnika posloženi da te Google nađe i bez plaćenih oglasa.' },
      { title: 'Cijena poznata unaprijed', note: 'Paketi s fiksnom cijenom i jasnim opsegom. Bez skrivenih stavki i naknadnih iznenađenja.' },
    ],
    packagesTitle: 'Koliko košta web stranica?',
    packagesSub: 'Tri paketa, fiksne cijene. Točnu ponudu dobiješ nakon prvog razgovora, bez skrivenih stavki.',
    packages: [
      {
        name: 'Start',
        price: PRICES.webStart,
        duration: '2-3 tjedna',
        tagline: 'Za male biznise koji trebaju profesionalan web, brzo i bez komplikacija.',
        features: [
          'Do 5 stranica (Naslovnica, O nama, Usluge, Kontakt...)',
          'Custom dizajn, bez predložaka',
          'Responzivni dizajn (mobitel, tablet, računalo)',
          'Kontakt forma',
          'Osnovna SEO optimizacija',
          'SSL certifikat',
          'Postavljanje hostinga i domene',
        ],
      },
      {
        name: 'Standard',
        price: PRICES.webStandard,
        duration: '3-5 tjedana',
        tagline: 'Za biznise koji žele web koji aktivno dovodi klijente.',
        features: [
          'Do 10 stranica',
          'Dizajn po mjeri s animacijama',
          'Copywriting tekstova',
          'Blog / Novosti sekcija',
          'Kontakt forma + newsletter prijava',
          'Napredna SEO optimizacija',
          'Google Analytics postavljanje',
          'Povezivanje društvenih mreža',
        ],
        highlight: true,
        badge: 'Najčešći izbor',
      },
      {
        name: 'Premium',
        price: PRICES.webPremium,
        duration: '5-8 tjedana',
        tagline: 'Kompletno digitalno rješenje za biznise koji misle ozbiljno.',
        features: [
          'Do 20 stranica',
          'Premium dizajn i animacije',
          'CMS: samostalno uređivanje sadržaja',
          'Copywriting tekstova',
          'Napredni SEO + Google Search Console',
          'Integracije (rezervacije, newsletter)',
          'Priprema za višejezičnost',
          'Prioritetna podrška 30 dana nakon lansiranja',
        ],
      },
    ],
    packagesNote: 'Trebaš nešto ekstra? Dodatni jezik, online rezervacije, fotografiranje ili Google poslovni profil dogovaraju se kao dodatak uz svaki paket.',
    steps: [
      { step: '01', title: 'Razgovor', note: 'Prođemo što trebaš, koliko košta i kad će biti gotovo.' },
      { step: '02', title: 'Dizajn', note: 'Prvo skice, pa dizajn. Ništa ne ide u razvoj dok ne kažeš da.' },
      { step: '03', title: 'Razvoj', note: 'Gradimo i testiramo na stvarnim uređajima.' },
      { step: '04', title: 'Lansiranje', note: 'Domena, hosting, analitika. I održavanje ako želiš.' },
    ],
    faqs: [
      { q: 'Koliko košta izrada web stranice?', a: `Paketi kreću od ${eur(PRICES.webStart)} za web do 5 stranica. Standard paket s dizajnom po mjeri i copywritingom je ${eur(PRICES.webStandard)}, a Premium s CMS-om i animacijama ${eur(PRICES.webPremium)}. Točnu ponudu dobiješ nakon prvog razgovora, bez skrivenih stavki.` },
      { q: 'Koliko traje izrada?', a: 'Start paket 2-3 tjedna, Standard 3-5, Premium 5-8. Najviše ovisi o tome koliko brzo stižu materijali i povratne informacije s tvoje strane.' },
      { q: 'Već imam web, može li se samo osvježiti?', a: 'Može. Pogledamo što ima smisla zadržati, što baciti, i predložimo redizajn koji ne kreće od nule ako ne mora.' },
      { q: 'Hoću li moći sam mijenjati sadržaj?', a: 'U Premium paketu dobiješ CMS pa sadržaj mijenjaš sam, kad god želiš. U ostalim paketima izmjene radimo mi, a CMS se uvijek može dogovoriti kao dodatak.' },
      { q: 'Što s održavanjem nakon lansiranja?', a: 'Imamo mjesečne pakete održavanja: ažuriranja, sigurnosne zakrpe, sitne izmjene sadržaja i podrška. Cijena ovisi o opsegu i dogovara se uz ponudu.' },
      { q: 'Kako izgleda suradnja?', a: 'Prvo razgovor, pa ponuda, pa posao. Tijekom projekta imaš direktan kontakt s nama, bez posrednika i bez čekanja tjedan dana na mail.' },
    ],
    formTitle: 'Zatraži ponudu',
    formSub: 'Reci nam što trebaš i javimo se unutar 24 sata s konkretnim prijedlogom.',
    formSubject: 'Upit s landing stranice · Izrada web stranica',
  },

  'izrada-web-shopa': {
    slug: 'izrada-web-shopa',
    chip: 'Izrada web shopa',
    metaTitle: `Izrada web shopa od ${eur(PRICES.shopMini)} | Ninefold`,
    metaDescription: `Izrada web shopa s online plaćanjem. Od mini trgovine od ${eur(PRICES.shopMini)} do shopa po mjeri. Dizajn koji prodaje, cijena poznata unaprijed.`,
    h1: 'Izrada web shopa koji prodaje.',
    sub: 'Od mini trgovine do shopa po mjeri: online plaćanje, jednostavno vođenje narudžbi i dizajn koji ne izgleda kao template.',
    heroPills: [`Mini shop od ${eur(PRICES.shopMini)}`, 'Online plaćanje uključeno', 'Odgovor unutar 24 sata'],
    benefits: [
      { title: 'Online plaćanje od prvog dana', note: 'Kartice i sigurna naplata posložene prije lansiranja. Kupac plati, ti dobiješ narudžbu.' },
      { title: 'Sam vodiš svoju trgovinu', note: 'Dodaješ proizvode, mijenjaš cijene i pratiš narudžbe bez zvanja programera.' },
      { title: 'Brzina i SEO', note: 'Shop koji se otvara ispod sekunde i koji Google nađe. Spor shop je prazan shop.' },
      { title: 'Dizajn po mjeri', note: 'Tvoja trgovina izgleda kao tvoj brend, ne kao tisuću drugih shopova na istoj temi.' },
    ],
    packagesTitle: 'Koliko košta web shop?',
    packagesSub: 'Za početak online prodaje ili za ozbiljan katalog. Točnu ponudu dobiješ nakon prvog razgovora.',
    packages: [
      {
        name: 'Mini web shop',
        price: PRICES.shopMini,
        duration: '3-4 tjedna',
        tagline: 'Za početak online prodaje, do 15 proizvoda.',
        features: [
          'Do 15 proizvoda',
          'Online plaćanje karticama',
          'Custom dizajn, bez predložaka',
          'Responzivni dizajn (mobitel, tablet, računalo)',
          'Upravljanje narudžbama',
          'Osnovna SEO optimizacija',
          'SSL certifikat',
          'Postavljanje hostinga i domene',
        ],
        highlight: true,
        badge: 'Najbrži start',
      },
      {
        name: 'Web shop po mjeri',
        price: null,
        priceNote: `od ${eur(PRICES.shopCustomFrom)}`,
        duration: 'po dogovoru',
        tagline: 'Za veće kataloge i posebne zahtjeve.',
        features: [
          'Neograničen broj proizvoda',
          'Dizajn i funkcionalnosti po mjeri',
          'Više načina plaćanja',
          'Integracije (dostava, newsletter, ERP)',
          'Napredna SEO optimizacija',
          'Edukacija za vođenje shopa',
          'Podrška nakon lansiranja',
        ],
      },
    ],
    packagesNote: 'Uz shop se često dogovaraju i copywriting opisa proizvoda, profesionalno fotografiranje proizvoda i dodatni jezik.',
    steps: [
      { step: '01', title: 'Razgovor', note: 'Prođemo asortiman, načine plaćanja i dostavu.' },
      { step: '02', title: 'Dizajn', note: 'Dizajn shopa i toka kupnje. Ništa ne ide dalje bez tvog da.' },
      { step: '03', title: 'Razvoj', note: 'Proizvodi, plaćanje i testne narudžbe od početka do kraja.' },
      { step: '04', title: 'Lansiranje', note: 'Domena, hosting, analitika i kratka edukacija za vođenje shopa.' },
    ],
    faqs: [
      { q: 'Koliko košta izrada web shopa?', a: `Mini web shop s do 15 proizvoda i online plaćanjem je ${eur(PRICES.shopMini)}. Shopovi po mjeri kreću od ${eur(PRICES.shopCustomFrom)}, ovisno o broju proizvoda i integracijama. Točnu ponudu dobiješ nakon prvog razgovora.` },
      { q: 'Mogu li sam dodavati proizvode?', a: 'Da. Dobiješ pristup administraciji u kojoj sam dodaješ proizvode, mijenjaš cijene i pratiš narudžbe. Pokažemo ti kako, traje pola sata.' },
      { q: 'Koje načine plaćanja podržavate?', a: 'Kartično plaćanje je standard u svakom shopu. Plaćanje virmanom ili pouzećem dodajemo po dogovoru, ovisno o tome kako želiš poslovati.' },
      { q: 'Koliko traje izrada?', a: 'Mini web shop 3-4 tjedna. Shop po mjeri ovisi o opsegu, okvirni rok dobiješ uz ponudu i držimo ga se.' },
      { q: 'Što s dostavom?', a: 'Posložimo cijene dostave i pravila po tvojim uvjetima, a integracije s dostavnim službama dogovaramo prema potrebi.' },
      { q: 'Već imam shop, može li redizajn?', a: 'Može. Pogledamo što radi, što ne radi i gdje kupci odustaju, pa predložimo redizajn ili prelazak na brže rješenje bez gubitka podataka.' },
    ],
    formTitle: 'Zatraži ponudu',
    formSub: 'Reci nam što prodaješ i javimo se unutar 24 sata s konkretnim prijedlogom.',
    formSubject: 'Upit s landing stranice · Izrada web shopa',
  },
}
